import type { LayoutLoad } from "./$types";

export const ssr = false;
export const prerender = true;
export const trailingSlash = 'always';

export const load = (async () => {
  return {
    result: [
      {
        Nome: 'Gabriel',
        'Total de Partidas Jogadas': 8393,
        'Vitória %': 64.7,
        'Gols (Total)': 15404,
        'Assistências': 4361,
        'Defesas': 10509,
        'Média de Gols por Partida': 1.8,
        'Média de Assistências por Partida': 0.52,
        'Média de Defesas por Partida': 1.3,
        'Nível de XP': 2315,
        'XP geral': 13084,
        'Tempo de Jogo (em horas)': 645,
        'Vitórias': 5433,
        'MVPs': 2887,
        'Gols Aéreos': 855,
        'Gols de Ré': 99,
        'Gols de Bicicleta': 43,
        'Gols à Distância': 1046,
        "Início do jogo": new Date("2016-01-01T00:00:00"),
      },
      {
        Nome: 'Michel',
        'Total de Partidas Jogadas': 7918,
        'Vitória %': 58.1,
        'Gols (Total)': 8885,
        'Assistências': 4861,
        'Defesas': 4141,
        'Média de Gols por Partida': 1.1,
        'Média de Assistências por Partida': 0.61,
        'Média de Defesas por Partida': 0.52,
        'Nível de XP': 1417,
        'XP geral': 8804,
        'Tempo de Jogo (em horas)': 616,
        'Vitórias': 4603,
        'MVPs': 1632,
        'Gols Aéreos': 623,
        'Gols de Ré': 59,
        'Gols de Bicicleta': 14,
        'Gols à Distância': 364,
        "Início do jogo": new Date("2024-07-01T00:00:00"),
      },
      {
        Nome: 'Dudu',
        'Total de Partidas Jogadas': 6209,
        'Vitória %': 57.4,
        'Gols (Total)': 7607,
        'Assistências': 3808,
        'Defesas': 5351,
        'Média de Gols por Partida': 1.2,
        'Média de Assistências por Partida': 0.61,
        'Média de Defesas por Partida': 0.86,
        'Nível de XP': 1990,
        'XP geral': 16011,
        'Tempo de Jogo (em horas)': 490,
        'Vitórias': 3567,
        'MVPs': 1324,
        'Gols Aéreos': 383,
        'Gols de Ré': 49,
        'Gols de Bicicleta': 18,
        'Gols à Distância': 417,
        "Início do jogo": new Date("2020-01-01T00:00:00"),
      },
      {
        Nome: 'Leandro',
        'Total de Partidas Jogadas': 6317,
        'Vitória %': 56.1,
        'Gols (Total)': 6287,
        'Assistências': 3717,
        'Defesas': 4422,
        'Média de Gols por Partida': 1,
        'Média de Assistências por Partida': 0.59,
        'Média de Defesas por Partida': 0.7,
        'Nível de XP': 1878,
        'XP geral': 3720,
        'Tempo de Jogo (em horas)': 499,
        'Vitórias': 3541,
        'MVPs': 895,
        'Gols Aéreos': 387,
        'Gols de Ré': 27,
        'Gols de Bicicleta': 11,
        'Gols à Distância': 329,
        "Início do jogo": new Date("2021-01-01T00:00:00"),

      },
    ] as Array<PlayerStat>,
  };
}) satisfies LayoutLoad;
